

ROOT=$(CURDIR)
OPDIR=$(ROOT)/../../
TESTDIR=$(ROOT)/test/


all:

runserver:
	export PYTHONPATH=$(OPDIR); poetry run $(ROOT)/server.py

test0:
	export PYTHONPATH=$(OPDIR); poetry run $(TESTDIR)/0clientinit.py


